v01 Solution
mate-academy/layout_product-cards-en pull request #55
Opened 2022-09-05 19:07 UTC by home2ego911

- [DEMO LINK](https://home2ego911.github.io/layout_product-cards-en/)
- [TEST REPORT LINK](https://home2ego911.github.io/layout_product-cards-en/report/html_report/)

2022-09-08 12:06 UTC, Bohdan-Maksymiuk requested changes
Good job - fix comments

2022-09-08 12:06 UTC, Bohdan-Maksymiuk commented on src/index.html
> +      <h1 class="product-title card__product-title">APPLE A1419 iMac 27" Retina 5K Monoblock (MNED2UA/A)</h1>
h1 should be 1 per all page
what will be if there will be several cards in catalogue ?

2022-09-08 12:06 UTC, Bohdan-Maksymiuk commented on src/index.html
> +      <div class="rating-wrapper card__rating-wrapper">
i believe that we can get rid of one of this selectors

2022-09-08 12:06 UTC, Bohdan-Maksymiuk commented on src/styles/blocks/product/card.css
> +}
these ones are block elements - no need for creating additional classes for external styles

2022-09-13 10:12 UTC, marina-tilniak requested changes
let's use BEM naming

2022-09-13 10:12 UTC, marina-tilniak commented on src/index.html
> +          class="product-image"
```suggestion
          class="card__product-image"
```

2022-09-13 10:12 UTC, marina-tilniak commented on src/index.html
> +        <p class="product-reviews">Reviews: 5</p>
```suggestion
        <p class="card__product-reviews">Reviews: 5</p>
```

2022-09-13 10:12 UTC, marina-tilniak commented on src/index.html
> +        <p class="product-quantity">$2,199</p>
```suggestion
        <p class="card__product-price">Price:</p>

        <p class="card__product-quantity">$2,199</p>
```

2022-09-13 13:07 UTC, closed without merging