Develop
mate-academy/layout_product-cards-en pull request #66
Opened 2022-10-18 12:19 UTC by Alessandranitti15

https://Alessandranitti15.github.io/layout_product-cards-en/
https://Alessandranitti15.github.io/layout_product-cards-en/report/html_report/

2022-10-18 17:00 UTC, Alessandranitti15 commented on src/button.css
> +.product-card__button {
<img width="1319" alt="Screenshot 2022-10-18 at 18 59 57" src="https://user-images.githubusercontent.com/101338498/196496978-3ee4da4f-5ab3-4009-9d5d-c5866bcf59a7.png">
Hello! I tried to create a block folder but now the page is broken. To me the path looks correct

2022-10-18 17:04 UTC, Alessandranitti15 commented on src/button.css
> +.product-card__button {
<img width="1464" alt="Screenshot 2022-10-18 at 19 04 07" src="https://user-images.githubusercontent.com/101338498/196497731-4f72b64c-1f80-4760-866b-03f4bb380128.png">
Hi, I tried to create the block folder and I think the path is correct but my page is broken :( I don't understand why

2022-10-20 09:08 UTC, amitpatiljc requested changes

2022-10-20 09:08 UTC, amitpatiljc commented on src/rating.css
> +}
how you changed naming for button and rating same way change for rating as well in `rating.css`

2022-10-20 09:08 UTC, amitpatiljc commented on src/styles/blocks/product.css
> +
for this file name should be same as block name `product-card.css`
or class name should be `product`

2022-10-20 09:12 UTC, amitpatiljc requested changes

2022-10-20 09:12 UTC, amitpatiljc commented on src/price.css
> +}
delete this file as you have this file already in blocks folder

2022-10-20 09:12 UTC, amitpatiljc commented on src/rating.css
> +}
delete this file as you have same file in blocks folder
and attach this file to your style.css

2022-10-20 12:35 UTC, closed without merging